### ISSUE TITLE
ParListWithSCSCP does not load all available slaves

### ISSUE THREAD

**Issue by markuspf** [gap-packages/scscp#2]
When running a computation with `128` slaves using `ParListWithSCSCP` the master does not load all available slaves.

**Comment by alex-konovalov** [comment]
What does "does not load all" means? If the number of tasks is bigger than 128, at least initial allocation should try to give one task to each worker. The rest depends on the task granularity. I think you may need to increase the size of the task.

**Comment by markuspf** [comment]
I mean that there is work available:

```
#I  2324/4180:master --> lovelace:26107
```

But about 48 of my slaves do not have work, they just sit idle.

**Comment by alex-konovalov** [comment]
This was displayed *after* the task number 2324 out of 4180 was sent to the worker at 26107. After that, the scheduler checks if there are any free services ready to accept calls, and if not it then it checks if there are any of the running tasks that are completed. It seems to me that the servers are idle because they completed the task, but are waiting till the master will retrieve its result. But because the task is not long enough, the master always reaches some other worker located closer to the beginning of the list of workers.

Maybe some tweaks of the scheduler may help - I need to think. But if you can try larger tasks and see if it helps, please do.

**Comment by markuspf** [comment]
I am not enthused about stopping a computation that will take ~3 days on 128 cores (nor do I have a way to start a second copy of this, since I don't have the resources)

**Comment by alex-konovalov** [comment]
This is a load balancing problem, depending on a particular computation. I've seen better load balancing on such large pools, so it should be improvable, but this issue does not provide enough information for more detailed investigation. I suggest to close it for now.
